# Generated by Django 2.1.3 on 2018-11-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20181105_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.CharField(default='good', max_length=10),
            preserve_default=False,
        ),
    ]
