# Generated by Django 2.1.3 on 2018-11-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userID',
            field=models.CharField(default='111111', max_length=50),
            preserve_default=False,
        ),
    ]
