# Generated by Django 2.1.3 on 2018-11-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_user_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='combined_weights',
        ),
        migrations.AddField(
            model_name='order',
            name='deliveredTime',
            field=models.DateTimeField(null=True),
        ),
    ]
