# Generated by Django 2.1.3 on 2018-11-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20181119_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispatchedTime',
            field=models.DateTimeField(null=True),
        ),
    ]
