# Generated by Django 2.1.3 on 2018-11-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_order_dispatchedtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='location',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='csv',
        ),
        migrations.AddField(
            model_name='pack',
            name='itinerary',
            field=models.ManyToManyField(to='login.Distance'),
        ),
        migrations.RemoveField(
            model_name='pack',
            name='order',
        ),
        migrations.AddField(
            model_name='pack',
            name='order',
            field=models.ManyToManyField(to='login.Order'),
        ),
        migrations.DeleteModel(
            name='Itinerary',
        ),
    ]
