# Generated by Django 2.1.3 on 2018-11-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20181120_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliver_record',
            name='order',
        ),
        migrations.RemoveField(
            model_name='dispatch_queue',
            name='order',
        ),
        migrations.RemoveField(
            model_name='dispatch_record',
            name='order',
        ),
        migrations.RemoveField(
            model_name='packing_queue',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shipping_lable',
            name='order',
        ),
        migrations.AddField(
            model_name='forget_password',
            name='token',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='orderTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Deliver_Record',
        ),
        migrations.DeleteModel(
            name='Dispatch_Queue',
        ),
        migrations.DeleteModel(
            name='Dispatch_Record',
        ),
        migrations.DeleteModel(
            name='Packing_Queue',
        ),
        migrations.DeleteModel(
            name='Shipping_Lable',
        ),
    ]
