# Generated by Django 2.1.3 on 2018-11-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20181201_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packed',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
